export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';


/*
*
* CHAT
*
* */
export const FECTH_MESSAGE_SUCCESS = 'FETCH_MESSAGE_SUCCESS';
export const FECTH_MESSAGE_ERROR = 'FETCH_MESSAGE_ERROR';


/*
*
* ROOM
*
* */
export const FETCH_ROOM_SUCCESS = 'FETCH_ROOM_SUCCESS';
export const FETCH_ROOM_ERROR = 'FETCH_ROOM_ERROR';

/*
*
* CONTACT
*
* */
export const FETCH_CONTACT_SUCCESS = 'FETCH_CONTACT_SUCCESS';
export const FETCH_CONTACT_ERROR = 'FETCH_CONTACT_ERROR';